'use client';

import { useRef, useState } from 'react';
import { AnswerCard } from '@/components/answer-card';
import { EmptyState, Spinner } from '@/components/states';
import { ALERT, BUTTON, BUTTON_SECONDARY, CARD, INPUT } from '@/components/styles';
import { apiFetch, messageOf } from '@/lib/api';
import type { Question } from '@/lib/types';

const MAX_QUESTION_CHARS = 1000;

type Props = { documentId: string; initialQuestions: Question[] };

export function QuestionPanel({ documentId, initialQuestions }: Props) {
  const [questions, setQuestions] = useState(initialQuestions);
  const [draft, setDraft] = useState('');
  // Whether the model searches the document itself: slower and uses more tokens
  const [agentic, setAgentic] = useState(false);
  const [pendingAgentic, setPendingAgentic] = useState(false);
  // The question being answered right now, shown in the "Thinking" card
  const [pending, setPending] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const input = useRef<HTMLTextAreaElement>(null);

  const trimmed = draft.trim();

  async function ask() {
    if (!trimmed || pending) return;
    setError(null);
    setPending(trimmed);
    setPendingAgentic(agentic);
    try {
      const answer = await apiFetch<Question>(`/documents/${documentId}/questions`, {
        method: 'POST',
        json: { question: trimmed, mode: agentic ? 'agentic' : 'classic' },
      });
      setQuestions((current) => [...current, answer]);
      // Clears only what was sent: the user may already be typing the next question
      setDraft((current) => (current.trim() === trimmed ? '' : current));
    } catch (cause) {
      // The draft is kept so the user can retry or edit it
      setError(messageOf(cause));
    } finally {
      setPending(null);
    }
  }

  function reask(text: string) {
    setDraft(text);
    input.current?.focus();
  }

  return (
    <div className="space-y-6">
      <form
        className={`${CARD} space-y-3`}
        onSubmit={(event) => {
          event.preventDefault();
          void ask();
        }}
      >
        <label className="block text-sm font-medium">
          Your question
          <textarea
            ref={input}
            rows={3}
            maxLength={MAX_QUESTION_CHARS}
            value={draft}
            onChange={(event) => setDraft(event.target.value)}
            className={INPUT}
          />
        </label>
        <label className="flex items-start gap-2 text-sm">
          <input
            type="checkbox"
            checked={agentic}
            disabled={pending !== null}
            onChange={(event) => setAgentic(event.target.checked)}
            className="mt-1"
          />
          <span>
            Let the model search the document <span className="text-slate-500">(slower, uses more tokens)</span>
          </span>
        </label>
        <div className="flex items-center justify-between gap-3">
          <p className="text-xs text-slate-500">
            Answers are generated by AI from your document. Check the sources before relying on them.
          </p>
          <button type="submit" disabled={pending !== null || !trimmed} className={BUTTON}>
            {pending ? 'Thinking…' : 'Ask'}
          </button>
        </div>
      </form>

      {error && (
        <div role="alert" className={`${ALERT} flex items-center justify-between gap-4`}>
          <span>{error}</span>
          <button type="button" onClick={() => void ask()} className={BUTTON_SECONDARY}>
            Try again
          </button>
        </div>
      )}

      {pending && (
        <article className={`${CARD} space-y-3`}>
          <h3 className="font-medium">{pending}</h3>
          <Spinner label={pendingAgentic ? 'Searching the document' : 'Thinking'} />
        </article>
      )}

      {questions.length === 0 && !pending && (
        <EmptyState title="Ask your first question" hint="The answer will cite the passages it was taken from." />
      )}

      <div className="space-y-4">
        {[...questions].reverse().map((question) => (
          <AnswerCard key={question.id} question={question} onReask={reask} />
        ))}
      </div>
    </div>
  );
}
